### ISSUE TITLE
PyQt5 Multiple Level Header View

### ISSUE THREAD

**Issue by mire22** [eyllanesc/QtExamples#2]
Hi!

I would like to make a multiple level header view for a QTableView. The example that you made in C++ [https://github.com/eyllanesc/stackoverflow/tree/master/questions/46469720](url) is exactly what I want but in Python.
So I translated all the code from C++ to Python with PyQt5 library. The results are that the vertical header works well but not the horizontal header: only the first line is displayed. I compared again and again the full code to find the error but I can't fix it.

You will find the full Python code attached and screenshots: [MultipleLevelHeaderView_python.zip](https://github.com/eyllanesc/QtExamples/files/5026401/MultipleLevelHeaderView_python.zip)
In GridTableHeaderView > PaintSection, I printed the cells data and the horizontal header cells are well created and painted... But at the end, they don't show.

Thank you for your help!
Rémi

**Images**
- Screenshot of the github web page [https://github.com/eyllanesc/stackoverflow/tree/master/questions/46469720](url):

![Screenshot_github](https://user-images.githubusercontent.com/35899128/89319640-ae7ff200-d680-11ea-9c10-baa960cc3c65.png)
- Screenshot when I run your C++ project:

![Screenshot_c++](https://user-images.githubusercontent.com/35899128/89319637-ade75b80-d680-11ea-949c-9eaf0f5eb76c.png)
Minor issues are that I don't see the horizontal lines in the headers and the cyan background doesn't show.
- Screenshot with the Python files translated from your C++ project:

![Screenshot_python](https://user-images.githubusercontent.com/35899128/89319642-af188880-d680-11ea-8884-e478618a4cbe.png)
I don't have the 2 lines in the horizontal header ("cell5" and "cell6" are lacking). Moreover "cell2" and "cell3" are not vertically centered in the vertical header.

**Environment:**
- OS: Windows 10
- Python version:  Python 3.7.3
- PyQt5 version: PyQt5 version 5.9.2 - Qt version 5.9.3

**Comment by eyllanesc** [comment]
@mire22 When executing your code in Linux with PyQt5 5.15 I get:

![](https://user-images.githubusercontent.com/4896200/89451567-09b5f100-d722-11ea-9849-2fcba9387123.png)

So I will review because some cells are not shown, the style seems strange to me but try putting: `app.setStyle("fusion")`, in addition to that tell me what you get when you run: `print(app.style().metaObject().className())`

**Comment by mire22** [comment]
With `app.setStyle("fusion")` the lines and the cyan background appear:
![Screenshot_python_fusion](https://user-images.githubusercontent.com/35899128/89497169-1be46d80-d7bc-11ea-992e-35ea7aa8ab84.png)
Command `print(app.style().metaObject().className())` returns:
- `QWindowsVistaStyle` without `app.setStyle("fusion")`
- `QFusionStyle` with `app.setStyle("fusion")`

**Comment by mire22** [comment]
Hi,
I just tried with Qt version 5.9.6 and it is the same.
I can't see how to solve this issue.
Thank you for your help.
Rémi

**Comment by mire22** [comment]
I found the bug! Christmas magic!
It was one tabulation too many...
For who may be interested: [MultipleLevelHeaderViewPython.zip](https://github.com/eyllanesc/QtExamples/files/5739410/MultipleLevelHeaderViewPython.zip)
